### ISSUE TITLE
topN query selecting rank 2-4 is inconsistently missing rows or showing extras with and without batch backfill

### ISSUE THREAD

**Issue by nparrish42** [fentik/flink#5]
```
WITH product_sales_totals AS (
    SELECT  product_name,
            category,
            SUM(CAST(quantity AS INT) * price) AS total_sales
        FROM order_items
        GROUP BY product_name, category
)
SELECT category, product_name, row_num
FROM (
    SELECT  product_name,
            category,
            row_number() OVER (PARTITION BY category
                            ORDER BY total_sales DESC) AS row_num
    FROM product_sales_totals)
    WHERE row_num BETWEEN 11 and 20;
```

there's also the "no row_num" variant of this where the second select is just `SELECT category, product_name` -- not including the rank in output materially changes the execution plan and failure behavior.

failures are inconsistent, but seem more prevalent with higher parallelism and with larger numbers of rows.
when I do `BETWEEN 2 and 3` to have a more manageable amount of output to study, I typically get consistent results).
also with parallelism of 1, the "with row_num" case typically passes. 

the nature of the failure is typically that additional rows are produced by non-batch-backfill -- there should be 220 rows, 10 products from each of 22 categories -- but non-batch-backfill will produce an extra 20-30 rows:
```
ResultMismatchError: backfill DISABLED unique rows:
Automotive, Plastic Handmade Pizza
Beauty, Wooden Handcrafted Ball
Clothing, Concrete Gently Used Cheese
Clothing, Frozen For repair Shoes
Clothing, Soft Handmade Car
Computers, Concrete Gorgeous Soap
Computers, Concrete Small Tuna
Games, Wooden Used Chips
Garden, Soft Practical Sausages
Grocery, Concrete Awesome Pizza
Grocery, Cotton Gently Used Keyboard
Grocery, Frozen Sleek Chicken
Health, Fresh Gently Used Tuna
Home, Metal Awesome Pants
Kids, Wooden Fantastic Gloves
Movies, Fresh Small Car
Outdoors, Granite Small Bike
Tools, Concrete Incredible Gloves
Tools, Wooden For repair Chicken
Toys, Rubber Sleek Bike
backfill ENABLED 220 results, backfill DISABLED 240
```

but I've also seen the query WITH row_num return with rows missing from batch-backfill mode results:
```
ResultMismatchError: backfill DISABLED unique rows:
Automotive, Concrete Handmade Pizza, 13
Automotive, Concrete Licensed Cheese, 15
...
backfill ENABLED 50 results, backfill DISABLED 220
```
this particular failure has proven more difficult to replicate, unless/until I crank parallelism to 8.

note I haven't yet built logic to validate results against postgres, I'm assuming when I get 220 results, it's the right ones.

**Comment by nparrish42** [comment]
I've now got validation against postgres, and with backfill enabled, the test fails about 25% of the time, and the failure looks like missing 7 categories (10 rows each) entirely:
```
ResultMismatchError: postgres 70 unique rows:
Books, Concrete Ergonomic Bike
Books, Concrete Gorgeous Keyboard
Books, Frozen For repair Pizza
Books, Granite Tasty Bacon
Books, Metal Awesome Soap
Books, Metal Ergonomic Gloves
Books, Rubber Gently Used Car
Books, Rubber Sleek Soap
Books, Steel Intelligent Pizza
Books, Wooden Generic Pizza
Computers, Concrete Handcrafted Pants
Computers, Concrete Intelligent Fish
Computers, Concrete Rustic Car
...
Jewelery, Soft Rustic Towels
Jewelery, Soft Used Pizza
Jewelery, Steel Gently Used Towels
Music, Cotton Awesome Salad
Music, Cotton Ergonomic Shoes
Music, Cotton Intelligent Shoes
Music, Frozen Sleek Car
Music, Metal Refined Cheese
Music, Plastic Rustic Keyboard
Music, Rubber Licensed Cheese
Music, Soft Sleek Soap
Music, Wooden Gently Used Table
Music, Wooden Practical Towels
postgres 220 results, dataflo 150
```
at least today, it's consistently been the same 70 rows missing.

**Comment by nparrish42** [comment]
running the same query with parallelism 1 never failed in 160+ iterations. 
it also seems like parallelism of 2 fails about as often as parallelism of 8 -- in any case, odds are we'll fail at least 1 in 10 tries either way, going to pass on further refining the odds here.

**Comment by nparrish42** [comment]
ah, but with parallelism of 2, when we fail, we lose 120 rows, parallelism 3 loses 110 rows...  parallelism 4 lost 70...  seems consistent (over a handful of runs, I'm not being rigorous here), so parallelism factor seems to influence the degree of data loss.

**Comment by nparrish42** [comment]
this appears to have been resolved by @sergeitsar 's latest fixes -- I looped parallelism 4 for 50+ iterations and saw no failures!

**Comment by nparrish42** [comment]
now testing 947cb28, this issue seems to still be with us, in particular I have here an example of batch-backfill enabled, SELECT includes the row_num, and we are missing 12 categories completely:
```
USE source_1;
SET pipeline.name='regression_test_de6068c7';
SET table.exec.sink.not-null-enforcer='DROP';
SET table.optimizer.agg-phase-strategy='ONE_PHASE';
SET sql-client.execution.result-mode='TABLEAU';
SET parallelism.default='2';
SET table.exec.source.cdc-events-duplicate='true';
SET table.exec.mini-batch.enabled='true';
SET table.exec.mini-batch.allow-latency='3 s';
SET table.exec.mini-batch.size='25000';
SET sql-client.display.max-column-width='10000';
SET table.exec.batch-backfill='true';
WITH product_sales_totals AS (
    SELECT  product_name,
            category,
            SUM(CAST(quantity AS INT) * price) AS total_sales
        FROM order_items
        GROUP BY product_name, category
)
SELECT category, product_name, row_num
FROM (
    SELECT  product_name,
            category,
            row_number() OVER (PARTITION BY category
                            ORDER BY total_sales DESC) AS row_num
    FROM product_sales_totals)
    WHERE row_num BETWEEN 11 and 20;
```
```
__main__.ResultMismatchError: postgres 120 unique rows:
Automotive, Concrete Handmade Pizza, 13
Automotive, Concrete Licensed Cheese, 15
Automotive, Cotton For repair Shirt, 17
Automotive, Cotton New Bike, 11
Automotive, Fresh Sleek Chips, 16
Automotive, Metal Awesome Pizza, 18
Automotive, Metal Fantastic Pizza, 20
Automotive, Metal Small Car, 19
Automotive, Metal Used Ball, 12
Automotive, Plastic Handcrafted Bike, 14
Books, Concrete Ergonomic Bike, 18
Books, Concrete Gorgeous Keyboard, 19
...
Music, Wooden Gently Used Table, 17
Music, Wooden Practical Towels, 20
Sports, Concrete Sleek Chair, 13
Sports, Cotton Generic Shirt, 17
Sports, Cotton Used Keyboard, 20
Sports, Fresh Fantastic Chips, 19
Sports, Fresh Generic Bacon, 16
Sports, Metal Ergonomic Pants, 15
Sports, Metal Gently Used Bike, 14
Sports, Rubber Licensed Sausages, 18
Sports, Wooden Handcrafted Salad, 12
Sports, Wooden Small Salad, 11
postgres 220 results, dataflo 100
```

**Comment by nparrish42** [comment]
this issue is still happening,  even with 8644cf2, which is the fix referenced in the prior comment, I am seeing the same kind of correctness problem, where some number of categories are missing entirely from the dataflo results.  and the number of categories missing seems to depend upon parallelism (e.g. testing with parallelism of 8, we miss the same set of 7 categories), but annoyingly the test sometimes passes even at high parallelism.

**Comment by sergeitsar** [comment]
hey @nparrish42 , what's a command line I can use to repro this?

**Comment by nparrish42** [comment]
ok, the problem here is that my test harness defaults to a "last result timeout" of 5 seconds, i.e. we assume we've finished streaming all the results if we pause for that long.  however, if we increase that timeout, see see that indeed we can have a pause for 5+ seconds, e.g.:
```
[2022-10-11T21:39:17.240+0000 INFO flink_regression_test] +I ['Outdoors', 'Steel Rustic Car', '20']
[2022-10-11T21:39:22.560+0000 INFO flink_regression_test] +I ['Computers', 'Frozen Sleek Chips', '11']
```
increasing the timeout to 60 seconds I'm successfully looping the test 10+ times now.
